-- Database: "QueixasNaNetDB"

-- DROP DATABASE "QueixasNaNetDB";

CREATE DATABASE "QueixasNaNetDB"
  WITH OWNER = "queixaUser"
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'Portuguese_Portugal.1252'
       LC_CTYPE = 'Portuguese_Portugal.1252'
       CONNECTION LIMIT = -1;

--Tables

CREATE TABLE CATEGORY (
	TITLE CHAR(50) PRIMARY KEY
);

CREATE TABLE LOCATION_COMPLAIN (
	LOCAL_COMPLAIN CHAR(20) PRIMARY KEY
);

CREATE TABLE USER_COMPLAIN (
	NICKNAME CHAR(50) PRIMARY KEY NOT NULL,
	USER_NAME CHAR(50) NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	USER_TYPE CHAR(13),
	USER_PASS CHAR(20),
	CHECK (USER_TYPE IN ('authenticated', 'non-auth', 'editor', 'admin'))
);

CREATE TABLE COMPLAIN (
	ID SERIAL PRIMARY KEY NOT NULL,
	TITLE CHAR(140) NOT NULL UNIQUE,
	DESCR TEXT,
	DATE_CRIADA DATE DEFAULT CURRENT_DATE,
	COMPLAINUP INTEGER DEFAULT 0,
	COMPLAINDOWN INTEGER DEFAULT 0, 
	CATEGORY_TITLE CHAR(50) REFERENCES CATEGORY(TITLE),
	LOCAL_COMP CHAR(20) REFERENCES LOCATION_COMPLAIN(LOCAL_COMPLAIN),
	USER_NICK CHAR(50) REFERENCES USER_COMPLAIN(NICKNAME)
);

CREATE TABLE COMMENT (
	ID_PK SERIAL NOT NULL,
	ID INTEGER DEFAULT 0,
	USER_NICK CHAR(50) REFERENCES USER_COMPLAIN(NICKNAME),
	ID_COMPLAIN INTEGER REFERENCES COMPLAIN(ID),
	PRIMARY KEY (ID_PK, ID_COMPLAIN, USER_NICK),
	COMMENT_TEXT TEXT NOT NULL,
	DATE_COMMENT DATE DEFAULT CURRENT_DATE
);

CREATE TABLE COMPLAIN_VOTE (
	USER_VOTE CHAR(50) REFERENCES USER_COMPLAIN(NICKNAME),
	ID_VOTE INTEGER REFERENCES COMPLAIN(ID),
	VOTE CHAR(4),
	PRIMARY KEY (USER_VOTE, ID_VOTE, VOTE)
);

CREATE TABLE COMPLAIN_FOLLOW (
	USER_FOLLOW CHAR(50) REFERENCES USER_COMPLAIN(NICKNAME),
	ID_FOLLOW INTEGER REFERENCES COMPLAIN(ID),
	PRIMARY KEY (USER_FOLLOW, ID_FOLLOW)
);

CREATE TABLE COMPLAIN_VIEW (
	USER_VIEW CHAR(50) REFERENCES USER_COMPLAIN(NICKNAME),
	ID_VIEW INTEGER REFERENCES COMPLAIN(ID),
	PRIMARY KEY (USER_VIEW, ID_VIEW)
);